### ISSUE TITLE
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

### ISSUE THREAD

**Issue by gmacario** [hackafake/hackafake-backend#32]
Warnings displayed when building docker image for service 'server'

```
gpmacario@nemo:~/github/hackafake/hackafake-backend (master)$ docker-compose up
Creating network "hackafakebackend_default" with the default driver
Building server
Step 1/12 : FROM debian:latest
 ---> 2b98c9851a37
Step 2/12 : RUN apt update &&     apt install python3 python3-pip -y &&     apt install nginx supervisor -y
 ---> Running in 90822fb6839e

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:3 http://security.debian.org stretch/updates InRelease [94.3 kB]
Get:4 http://deb.debian.org/debian stretch Release [118 kB]
Get:5 http://deb.debian.org/debian stretch Release.gpg [2434 B]
Get:6 http://security.debian.org stretch/updates/main amd64 Packages [468 kB]
Get:7 http://deb.debian.org/debian stretch-updates/main amd64 Packages [5476 B]
Get:8 http://deb.debian.org/debian stretch/main amd64 Packages [9500 kB]
Fetched 10.3 MB in 4s (2418 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
8 packages can be upgraded. Run 'apt list --upgradable' to see them.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
```

**Comment by taggsoft** [comment]
I do not understand what you mean here by Use "apt-get" instead of "apt"

**Comment by cqh963852** [comment]
> I do not understand what you mean here by Use "apt-get" instead of "apt"

`RUN apt update` -> `RUN apt-get update`

**Comment by maisonhai3** [comment]
As I know,

```
apt gives beautiful output for human reading so being preferred in the terminal.

apt-get does not give as nice outputs as apt but works great in scripts.
```

Since Dockerfile is kind of scripts, Docker recommends us to directly use the apt-get for installing sort of stuff.

Here you can get an inference.
https://askubuntu.com/questions/990823/apt-gives-unstable-cli-interface-warning

**Comment by ghost** [comment]
Get this error than using `QProcess` with the command `apt list`, has someone any ideas on how to fix this error

Simple example

`
#include <QCoreApplication>
#include <QProcess>
#include <QDebug>
int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    const QStringList commands={"-c" , " apt list"};
    QProcess process;
    process.start("/bin/sh", commands);
    process.waitForFinished(-1);
    QString processError = process.readAllStandardError();
    QString processOutput = process.readAllStandardOutput();
    if (processError != "") {
       qInfo() << processError;
       QString error=QString("Работа невозможна метод: выдал ошибку при комманде %2 . Cообщение об ошибке %3").arg(commands.last()).arg(processError);
       qFatal("%s", error.toUtf8().data());
    }
    process.close();
    return a.exec();
}

`

`aptitude -F %p search '!~i'` show no errors

**Comment by bhavyawadhwa856** [comment]
> > I do not understand what you mean here by Use "apt-get" instead of "apt"
> 
> `RUN apt update` -> `RUN apt-get update`

I am facing the same warning after I am using apt-get.

**Comment by burtsevyg** [comment]
apt != apt-get

```
$ sudo apt list --installed | grep libreoffice

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
```

```
sudo apt-get list --installed | grep libreoffice
E: Command line option --installed is not understood in combination with the other options
```
